# -*- coding: utf-8 -*-
"""python_03_Tuple_Set.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aKTLENH0dskHGYWTWVYPlr0pIdWvQuko

tuple 정의
"""

t1=()
t2=(1,2,3,4,5)
t3=(2,4,'판다',"강아지") # 컬렉션 타입(여러개 자료형 가능)

print(t2[0])
# 인덱싱을 통해 튜플 내부 데이터 접근 가능
# 파이썬은 0에서 시작
# -1: 뒤에서부터 시작
print() # 공백

print(t3[-2])

# slicing

# >> 튜플 안의 값의 일부만 가져오기

print(t2[4:3:-1])
print(t2[::-1]) # 역순으로 -1칸씩

t1=(1,2,3)
t2=(4,5,6)
t3=t1+t2
print(t3)

t4=(1,2,3,4)
# t4[-2]=5
# 튜플은 값을 임의 변경 불가(imutable)
# TypeError TypeError: 'tuple' object does not support item assignment

t4=list(t4)
print(t4)
print()
tuple(t4)

t5= t1*5
print(t5)

"""셋(set)"""

s1=()
# 곱하기로 만든 튜플을 set에 넣어보죠
t4=(1,2,3,4,5)
s2=set(t4)
print(s2)

type({1,2,3})

t4=list(t4) # tuple >> list
print(t4[2])

#  리스트로 바꿔보면?

t4.extend([4])
print(t4)

t4=set(t4)
# t4[0]>> 순서가 없으므로 indexing 이 안된다. TypeError: 'set' object is not subscriptable
# list, tuple is subscriptive

# 한 개의 값 추가 .add()
s2.add(6)
print(s2)

# 여러 개의 값 추가
print(s2)
s2.update([3,4,5,6,7,8])
print(s2)

# 특정 값 제거 .remove()
s2={1,2,3,4,5,6,7}
print(s2)
s2.remove(1)
print(s2)

"""교집합, 차집합, 합집합"""

# 교집합
t2=set([1,2,3,4,5])
t3={2,4,'판다','강아지'}
print(t2.intersection(t3))

# 차집합
print(t2.difference(t3))

# 합집합
print(t2.union(t3))
print(t2|t3)

