# -*- coding: utf-8 -*-
"""python_02_비교연산자.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S7r_Ra_pbc3gqEaDGyxQfgio1N6C198L

비교연산자 활용하기
"""

print(3==3)

ans1= 3==3
print(ans1)

3==3 and 2<4 and 3<5

(4>6) or ("apple"=="Apple") or (1==1)

not (False)

# 비교연산자 적용, 반복문 만들기

num=int(input()) # input()으로 사용자가 받은  >> string
# int() 정수를 만들어주는 함수. 문자 > 숫자


if num%2==0: # 나머지
  print(num, "even")
else:
  print(num, "odd")

ans=25

submit=int(input("number 1-50 "))

if ans==submit:
  print("correct!!")
elif ans>submit:
  print("higher!")
else:
  print("lower!")

